--

language: python
os: linux
dist: xenial
python:
  - 3.8
  - 3.9
before_install:
  - python --version
  - pip install -U pip
install:
  - pip install .
  - pip install -r requirements_test.txt  # install package deps and test deps
script: pytest
